---
{{- $serviceEnable := hasKey .Values.service "enabled" | ternary .Values.service.enabled true }}
{{- if $serviceEnable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.env }}-{{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
    release: {{ .Release.Name }}
  clusterIP: None 
  ports:
    {{- range $key, $value := .Values.image.port }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $value }}
    {{- end }}
{{- end }}