---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.env }}-{{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.image.replicas }}
  serviceName: {{ .Values.app.env }}-{{ .Values.app.name }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.app.env }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        env: {{ .Values.app.env }}
        release: {{ .Release.Name }}
    spec:
      securityContext: {{- toYaml .Values.image.securityContext | nindent 8 }}
      containers:
      - name: {{ .Values.app.env }}-{{ .Values.app.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        env:
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: app_name
          value: {{ .Values.app.name | quote }}
        - name: app_env
          value: {{ .Values.app.env | quote }}
        {{- if .Values.image.env }}
        {{- range $key, $value := .Values.image.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- $envSecretEnabled := hasKey .Values.image "envSecretEnabled" | ternary .Values.image.envSecretEnabled false }}
        {{- if $envSecretEnabled }}
        envFrom:
        - secretRef:
            name: {{ .Values.app.env }}-{{ .Values.app.name }}
        {{- end }}
        ports:
        {{- range $key, $value := .Values.image.port }}
        - name: {{ $key }}
          containerPort: {{ $value }}
        {{- end }}
        {{- $healthCheckEnabled := hasKey .Values.image "healthCheckEnabled" | ternary .Values.image.healthCheckEnabled true }}
        {{- if $healthCheckEnabled }}
        startupProbe:
          {{- if eq "tcp" (lower .Values.image.healthCheckMode) }}
          tcpSocket:
          {{- end }}
          {{- if eq "grpc" (lower .Values.image.healthCheckMode) }}
          grpc:
          {{- end }}
            port: {{ .Values.image.healthCheckPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          {{- if eq "tcp" (lower .Values.image.healthCheckMode) }}
          tcpSocket:
          {{- end }}
          {{- if eq "grpc" (lower .Values.image.healthCheckMode) }}
          grpc:
          {{- end }}
            port: {{ .Values.image.healthCheckPort }}
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          {{- if eq "tcp" (lower .Values.image.healthCheckMode) }}
          tcpSocket:
          {{- end }}
          {{- if eq "grpc" (lower .Values.image.healthCheckMode) }}
          grpc:
          {{- end }}
            port: {{ .Values.image.healthCheckPort }}
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
        resources:
        {{- toYaml .Values.image.resources | nindent 10 }}
        volumeMounts:
        - name: {{ .Values.app.env }}-{{ .Values.app.name }}
          mountPath: {{ .Values.pvc.mountPath }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.app.env }}-{{ .Values.app.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.app.env }}-{{ .Values.app.name }}